githubRepoOwner: mattskl-openai
githubRepoName: spr
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: true
requireApproval: false
mergeMethod: squash
mergeQueue: false
forceFetchTags: false
prPrefix: mattskl
